export const schema = {
  config: {
    defaultValues: {
      firstName: '',
      lastName: '',
      age: null,
      country: null,
      dateOfBirth: null,
      fileUpload: null,
    },
    submitButton: {
      display: 'flex',
      justifyContent: 'right',
      variant: 'contained',
      color: 'primary',
    },
  },
  fields: [
    {
      name: 'firstName',
      label: 'First Name',
      type: 'text',
      placeholder: 'Enter your first name',
      order: 1,
      rules: {
        type: 'string',
        required: true,
        message: 'First name is required',
      },
    },
    {
      name: 'lastName',
      label: 'Last Name',
      type: 'text',
      placeholder: 'Enter your last name',
      order: 2,
      rules: {
        type: 'string',
        required: true,
        message: 'Last name is required',
      },
    },
    {
      name: 'age',
      label: 'Age',
      type: 'number',
      placeholder: 'Enter your age',
      order: 3,
      rules: {
        type: 'number',
        required: true,
        message: 'Age is required',
        typeError: 'Age must be a number',
        positive: true,
        integer: true,
      },
    },
    {
      name: 'country',
      label: 'Country',
      type: 'dropdown',
      placeholder: 'Select your country',
      options: [
        { label: 'USA', value: 'usa' },
        { label: 'Canada', value: 'canada' },
        { label: 'UK', value: 'uk' },
        { label: 'Australia', value: 'australia' },
      ],
      order: 4,
      rules: {
        type: 'string',
        required: true,
        message: 'Country is required',
      },
    },
    {
      name: 'dateOfBirth',
      label: 'Date of Birth',
      type: 'date',
      placeholder: 'Select your date of birth',
      order: 5,
      rules: {
        type: 'date',
        required: false,
        nullable: true,
        message: 'Date of Birth is required',
      },
    },
  ],
};
